import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "BorderlessTek",
  description: "Generated by BorderlessTek",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
